### ISSUE TITLE
Multiple minor bugs that arose trying to get training to run

### ISSUE THREAD

**Issue by nelson-lojo** [in-context-learning-2024/in-context#47]

**Comment by Famara72** [comment]
Curriculum training does not work properly as of now. There are two bugs:
1. The curriculum training starts at the second value instead of the first. e.g. if we have start:1, end:4, step_size:1, we start at 2 instead of 1. 
2. The sequence length does not change during training. So if we have start:11, end:41, step_size: 2, we will only train with sequence length 13
